# Composite action for Terraform operations
# Usage: reference this action as a step in your workflow

name: 'Terraform Composite Action'
description: 'Run Terraform plan/apply/destroy as a step'
inputs:
  action:
    description: 'Terraform action to perform (plan/apply/destroy)'
    required: false
    default: 'plan'
  terraform_version:
    description: 'Terraform version to use'
    required: false
    default: '1.6.0'
  tf_target_module:
    description: 'Terraform target module (used in plan/destroy). Leave blank to target all.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Terraform Format Check
      working-directory: terraform
      shell: bash
      run: terraform fmt -check

    - name: Terraform Init
      working-directory: terraform
      shell: bash
      run: terraform init

    - name: Terraform Validate
      working-directory: terraform
      shell: bash
      run: terraform validate

    - name: Terraform Plan
      if: inputs.action == 'plan'
      id: plan
      working-directory: terraform
      shell: bash
      run: |
        set +e
        if [ -n "${{ inputs.tf_target_module }}" ]; then
          terraform plan -target="module.${{ inputs.tf_target_module }}" -detailed-exitcode -no-color -out=tfplan | tee plan.log
        else
          terraform plan -detailed-exitcode -no-color -out=tfplan | tee plan.log
        fi
        PLAN_EXIT_CODE=${PIPESTATUS[0]}
        echo "exitcode=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT
        cat plan.log > plan_output.txt
        if [ $PLAN_EXIT_CODE -eq 1 ]; then
          echo "❌ Terraform plan failed"
          exit 1
        fi
        echo "✅ Terraform plan completed with exit code: $PLAN_EXIT_CODE"

    - name: Comment PR with Plan
      if: github.event_name == 'pull_request' && inputs.action == 'plan'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('terraform/plan_output.txt', 'utf8');
          const exitCode = process.env.exitcode || '';
          let status = '';
          if (exitCode === '0') {
            status = '✅ No changes detected';
          } else if (exitCode === '2') {
            status = '📋 Changes detected';
          } else {
            status = '❌ Plan failed';
          }
          const output = `## Terraform Plan Results ${status}\n\n<details><summary>Show Plan Output</summary>\n\n\u0060\u0060\u0060terraform\n${plan}\n\u0060\u0060\u0060\n\n</details>\n\n*Plan Exit Code: ${exitCode}*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });

    - name: Terraform Apply
      if: inputs.action == 'apply'
      working-directory: terraform
      shell: bash
      run: |
        terraform apply -auto-approve tfplan
        echo "Infrastructure deployed successfully!"

    - name: Terraform Destroy
      if: inputs.action == 'destroy'
      working-directory: terraform
      shell: bash
      run: |
        if [ -n "${{ inputs.tf_target_module }}" ]; then
          terraform destroy -target="module.${{ inputs.tf_target_module }}" -auto-approve
        else
          terraform destroy -auto-approve
        fi
        echo "Infrastructure destroyed successfully!"

    - name: Output All Terraform Outputs
      if: inputs.action == 'apply'
      working-directory: terraform
      shell: bash
      run: |
        echo "## Terraform Outputs" >> $GITHUB_STEP_SUMMARY
        terraform output -json > tf_outputs.json
        if [ -s tf_outputs.json ]; then
          jq -r 'to_entries[] | "- **\(.key)**: \(.value.value)"' tf_outputs.json >> $GITHUB_STEP_SUMMARY
        else
          echo "No outputs found." >> $GITHUB_STEP_SUMMARY
        fi
        echo "\n---" >> $GITHUB_STEP_SUMMARY
        echo "*All available Terraform outputs have been listed above.*" >> $GITHUB_STEP_SUMMARY
